name: alsat
version: 1.0.0+1
publish_to: none
description: start your project in the fastest way
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.6.6 
  logger: ^2.3.0 
  flutter_screenutil: ^5.9.3 
  dio: ^5.4.3+1 
  shared_preferences: ^2.2.3 

  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  flutter_advanced_switch: ^3.1.0
  cached_network_image: ^3.4.0
  pull_to_refresh: ^2.0.0
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  widget_and_text_animator: ^1.1.5
  smooth_page_indicator: ^1.2.0+3
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  glassmorphism: ^3.0.0
  carousel_slider: ^5.0.0
  chatview:
    path: packages/chatview
    
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0

 



dev_dependencies:
  mockito:
  flutter_lints:

  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/appicon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900

