name: alsat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # notification package
  awesome_notifications_core: ^0.10.0
  awesome_notifications: any
  flutter_local_notifications:
  # other packages
  flutter_rating_bar: ^4.0.1
  wechat_assets_picker: ^9.3.1
  # video_thumbnail: ^0.5.3
  flutter_svg: ^2.0.10+1
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  emoji_picker_flutter: ^3.1.0
  modal_bottom_sheet: ^3.0.0
  mqtt_client: ^9.6.8
  path: ^1.9.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_crashlytics: ^4.1.4
  skeletonizer: ^1.4.2
  google_maps_flutter: ^2.9.0
  google_fonts: ^6.2.1
  flutter_advanced_switch: ^3.1.0
  cached_network_image: ^3.4.0
  pull_to_refresh: ^2.0.0
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  intl: any
  widget_and_text_animator: ^1.1.5
  smooth_page_indicator: ^1.2.0+3
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  glassmorphism: ^3.0.0
  carousel_slider: ^5.0.0
  
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  fl_chart: ^0.69.0
  get: ^4.6.6
  logger: ^2.3.0
  flutter_screenutil: ^5.9.3
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  pinput: ^5.0.0
  location: ^6.0.2
  geocoding: ^3.0.0
  get_thumbnail_video: ^0.7.3
  video_player: ^2.9.2
  flick_video_player: ^0.9.0
  pod_player: ^0.2.2
  video_editor:
    path: packages/video_editor
  video_trimmer:
    path: packages/video_trimmer-3.0.1
  simple_chips_input: ^1.2.0
  xml: ^6.5.0
  voice_message_package: ^2.2.1
  audio_waveforms: ^1.2.0
  crypto: ^3.0.6
  photo_view: ^0.15.0
  toastification: ^2.3.0
  form_builder_extra_fields: ^11.0.0
  flutter_slidable: ^3.1.2
  flutter_popup: ^3.3.0
  record: ^5.2.0
  flutter_material_pickers: ^3.7.0
  stories_for_flutter:
    path: packages/stories
  pro_image_editor: ^6.2.1


    
dev_dependencies:
  mockito:
  flutter_lints:

  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/appicon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Regular.ttf