class Constants {
  static const baseUrl = 'https://alsat-api.flutterrwave.pro/app/v1';
  static const token1 =
      'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyZDBjYjcyZS1jOTI3LTQzYTQtODdkNC01ZDczOWE3MmQ0OGYiLCJhdWQiOiJtb2JpbGUiLCJpc3MiOiJBbHNhdCBBUEkiLCJzdWIiOiJiNWUzNjJlYS1jOTI1LTQ5YzItOWU1Yy0zZWIxMmI4MWY5YWEiLCJleHAiOjE3MzQwMDY1ODYsImlhdCI6MTczMjcxMDU4NiwibmJmIjoxNzMyNzEwNTg1LCJhdXRoZW50aWNhdGVkIjp0cnVlLCJ0d29fZmFfYXV0aGVudGljYXRlZCI6ZmFsc2V9.v8iiILS1tresFSqbHllTNUSjwbkUIqZXgd6KqyFqlHMBM1FIexJL5kfbNPOyATfrkgyFTs11Dz5zMVtu981u8YNSueCv8kg9zctTWkOx-J1NOm7kirQCc7A4Vy3rlve_CzMRGJFnd1kyY_EVIaSr1w51Ca3yhgfjayh5wjcQPlHfq4wtD3lsq0lDobvxNKKnyhsV1FCsKJhg-mrrTL4upW-rPA9DK1iYJS7lFFDLhDuFii2RdlzMX8P5iHhmOU-ARTTlGloCOxk2WPXQTNAIY_g6OIM7lzlKHbhljmn4a8RHWe3Nge-_A87YeJpXCyUIAcUSZ84T5AaJt5hEOUcPAQ';
  static const token = 'Bearer $token1';
  static const filter = '/posts';

  static const getOtp = '/otp';
  static const varifyOtp = '/join';

  static const userProfile = '/users/profile';
  static const userConversationList = '/chats';
  static const conversationMessages = '/messages';
  static const postProduct = '/posts';
  static const categories = '/categories';
  static const banners = '/banners';
  static const user = '/users';
  static const fcmStore = '/users/device';
  static const follower = '/users/followers';
  static const following = '/users/following';
  static const carBrandEndPoint = '/carBrands?limit=200000';
}
//eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxYjk5YWU0NS0yYWJkLTQ3NTYtOWYxMC1iYzY0M2QzMzc2MjciLCJhdWQiOiJtb2JpbGUiLCJpc3MiOiJBbHNhdCBBUEkiLCJzdWIiOiI0YjJkYzZjNi1hZjU4LTQ5YzMtYjdjYi1lNWVmNGYwYjIyMjMiLCJleHAiOjE3MzA0ODc1MjgsImlhdCI6MTcyOTE5MTUyOCwibmJmIjoxNzI5MTkxNTI3LCJhdXRoZW50aWNhdGVkIjp0cnVlLCJ0d29fZmFfYXV0aGVudGljYXRlZCI6ZmFsc2V9.u3fBzldh5aVWk4y0NtKZgXyuS_v_gSVtBrUusRQMesehEC3LXPTqrhFlpF7BUF7tGllkS5muYIFmSjACL5iuljgtPCuBYhe5NtaplHJvi86mGsJNWH8eEAtYZHy1qwQZxaN9zR5s-pZ1q5MVEhjtZ3gHY9m7fmKJjTevi3e38QFiLacfGjPj2TSGhn8X3RJk6OtAKR8y5xgkMsoauEjTa--TebCxiLZdnR25W6VIb7K7Pn_R1Pc7H7ouHHOx--b5kibnyxNqLrKDZj1FXrWfu29fdl3ciz-48pan8TooblBHkgNLkCXY-2rr4_2BzWX1lRNDNC15XxLsHvoOEgKzeA
///eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI0YTA3MGI2NS0wMzFkLTQ1NWItYmNjNy03MGM4MzQwNTU2M2UiLCJhdWQiOiJtb2JpbGUiLCJpc3MiOiJBbHNhdCBBUEkiLCJzdWIiOiJkZGEwMTQxNS01ZWViLTQ3MTItYjk1Mi0wYTE0MTY4NmNjMjQiLCJleHAiOjE3MzA5MDQ1MDEsImlhdCI6MTcyOTYwODUwMSwibmJmIjoxNzI5NjA4NTAwLCJhdXRoZW50aWNhdGVkIjp0cnVlLCJ0d29fZmFfYXV0aGVudGljYXRlZCI6ZmFsc2V9.U2hkre5TyXFMTubDhQXnnEJzoJ1CjQstiwMMNwqcTFcSp4Oae2PlgRT1iD6vx9SuEYOzt_a2LSn0KPWIGRsruv_0_orzRd3xPNh6uhiWywj8VYanTWg5DeVuorbeE_tXiJLYbIgdSFacFh2nmPykQ3UYEyogTxKKupaO-x_h52PKD37y3lBneBhsAfwnVwM_D9Js_xcvhoD2Yf5DNAXq5Onr2a48muS8s5zIn2kwdn_FkQzPPAN3A6k8cp7OPjK7Ghn-hID10vtfS15AcPw9llpqtjGvZ5G_ygshgGvKYsxvMU3XCZad6Jx0LWojL7x-_Mmn4qUV_JkBArQu4Kcu5g