// ignore_for_file: non_constant_identifier_names

class Province {
  final String name;
  final List<String> cities;

  Province({
    required this.name,
    required this.cities,
  });
}

class SelectedProvince {
  final String province;
  final List<String> cities;

  SelectedProvince({required this.province, this.cities = const []});
}

//English Location
List<Province> provinces = [
  Province(name: "Ashgabat", cities: [
    "Parahat 1",
    "Parahat 2",
    "Parahat 3",
    "Parahat 4",
    "Parahat 5",
    "Parahat 6",
    "Parahat 7",
    "1 micro district",
    "2 micro district",
    "3 micro district",
    "4 micro district",
    "5 micro district",
    "6 micro district",
    "7 micro district",
    "8 micro district",
    "9 micro district",
    "10 micro district",
    "11 micro district",
    "30 micro district",
    "Howdan A",
    "Howdan B",
    "Howdan W",
    "13 stage",
    "14 stage",
    "15 stage",
    "16 stage",
    "Archabil avenue",
    "Chandybil avenue",
    "Neutrality avenue (Podvoyskaya)",
    "Independence avenue (Sovetskaya)",
    "Turkmenbashy avenue (Lenin)",
    "Neutral Turkmenistan avenue (Gogol)",
    "Magtymguly avenue",
    "A.Niyazov st",
    "10 year gratitude st",
    "Ataturk st",
    "Mati Kosayev st",
    "Gorogly st (Perwomay)",
    "Azady st",
    "A.Berdiew st (Yerewan)",
    "Taslama st",
    "Gundogar st (Magistral)",
    "Kemine st",
    "Bagtyyarlyk st",
    "G.Kulyev st (Obyezdnoy)",
    "Nagina st",
    "Petrozavod st",
    "Olimpic city",
    "Dosaf",
    "Neftegaz",
    "Ak Altyn rayon",
    "Koshi",
    "Kim rayon",
    "Taze zaman",
    "Yalkym",
    "Gypjak",
    "Yasmansalyk",
    "Akdashayak",
    "Bedew",
    "Arzuw",
    "Bagyr",
    "Choganly",
    "Gurtly",
    "Abadan (Buzmeyin)",
    "Hitrowka",
    "Promzona",
    "Eksbaza",
    "Herrikgala",
    "Bekrewe",
    "Gokje",
    "Ruhabat (90)",
    "Shor garadamak",
    "40 yyllyk",
    "Ashgabat mall",
    "Berkarar shopping center",
    "Arkach shopping center",
    "Bagtyyarlyk shopping center",
    "15 year Neutrality shopping center",
    "Gulzemin shopping center",
    "Ashgabadyn yalkymy shopping center",
    "Altyn zaman shopping center",
    "Altyn asyr Commodity center",
    "Univermag shopping center",
    "Paytagt shopping center"
  ]),
  Province(
    name: "Arkadag",
    cities: [],
  ),
  Province(name: "Ahal", cities: [
    "Anew",
    "Yashlyk",
    "Gokdepe",
    "Ak bugday",
    "Babadayhan",
    "Kaka",
    "Tejen",
    "Sarahs",
    "Baherden",
  ]),
  Province(name: "Dashoguz", cities: [
    "Dashoguz city",
    "Gurbansoltan eje",
    "Boldumsaz",
    "Gubadag",
    "Shabat",
    "Gorogly (Tagta)",
    "Akdepe",
    "Koneurgench",
    "S.Turkmenbashy",
    "Ruhubelent",
  ]),
  Province(name: "Mary", cities: [
    "Mary city",
    "Yoloten",
    "Murgap",
    "Sakarchage",
    "Serhet abat (Gushgy)",
    "Garagum",
    "Wekilbazar",
    "Shatlyk",
    "Bayramaly",
    "Turkmen gala",
    "Oguz han",
    "Tagta bazar",
  ]),
  Province(name: "Lebap", cities: [
    "Turkmenabat",
    "Halach",
    "Kerki",
    "Seydi",
    "Sayat",
    "Sakar",
    "Gazojak",
    "Garabekewil",
    "Farap",
    "Darganata",
    "Danew",
    "Kerki", // duplicate, if intentional it can stay
    "Koytendag",
    "Hojambaz",
    "Kerki", // another duplicate
    "Dostluk",
    "Magdanly",
  ]),
  Province(name: "Balkan", cities: [
    "Balkanabat",
    "Turkmenbashy",
    "Awaza",
    "Jebel",
    "Gumdag",
    "Gyzylarbat",
    "Garabogaz",
    "Esenguly",
    "Etrek",
    "Magtymguly",
    "Bereket",
  ]),
];

//Turkmen Location
List<Province> provinces_tr = [
  Province(name: "Aşgabat", cities: [
    "Parahat 1",
    "Parahat 2",
    "Parahat 3",
    "Parahat 4",
    "Parahat 5",
    "Parahat 6",
    "Parahat 7",
    "1-nji mikroraýon",
    "2-nji mikroraýon",
    "3-nji mikroraýon",
    "4-nji mikroraýon",
    "5-nji mikroraýon",
    "6-njy mikroraýon",
    "7-nji mikroraýon",
    "8-nji mikroraýon",
    "9-njy mikroraýon",
    "10-njy mikroraýon",
    "11-nji mikroraýon",
    "30-njy mikroraýon",
    "Howdan A",
    "Howdan B",
    "Howdan W",
    "13-nji tapgyr",
    "14-nji tapgyr",
    "15-nji tapgyr",
    "16-njy tapgyr",
    "Arçabil şaýoly",
    "Çandybil şaýoly",
    "Bitaraplyk şaýoly (Podwoýskaja)",
    "Garaşsyzlyk şaýoly (Sowetskaýa)",
    "Türkmenbaşy şaýoly (Lenin)",
    "Bitarap Türkmenistan şaýoly (Gogol)",
    "Magtymguly şaýoly",
    "A. Nyýazow köçesi",
    "10 ýyl Abadançylyk köçesi",
    "Atatürk köçesi",
    "Mäti Kosäýew köçesi",
    "Gorkut Ata köçesi (Pervomay)",
    "Azady köçesi",
    "A. Berdiýew köçesi (Ýerewan)",
    "Taslama köçesi",
    "Gündogar köçesi (Magistral)",
    "Kemine köçesi",
    "Bagtyýarlyk köçesi",
    "G. Kulyýew köçesi (Obýezdnoý)",
    "Nagina köçesi",
    "Petrozawod köçesi",
    "Olimpiýa şäherçesi",
    "DOSAAF",
    "Nebitgaz",
    "Ak Altyn raýony",
    "Köşi",
    "Kim raýon",
    "Täze zaman",
    "Ýalkym",
    "Gypjak",
    "Ýasmansalyk",
    "Akdaşaýak",
    "Bedev",
    "Arzuw",
    "Bagyr",
    "Çoganly",
    "Gurtly",
    "Abadan (Büzmeýin)",
    "Hitrowka",
    "Promzona",
    "Eksbaza",
    "Herrikgala",
    "Bekrewe",
    "Gökje",
    "Ruhabat (90)",
    "Şor Garadamak",
    "40 ýyllyk",
    "Aşgabat söwda merkezi (Ashgabat mall)",
    "Berkarar söwda merkezi",
    "Arkadag söwda merkezi",
    "Bagtyýarlyk söwda merkezi",
    "Bitaraplygyň 15 ýyllygy söwda merkezi",
    "Gülzemin söwda merkezi",
    "Aşgabadyň Ýalkymy söwda merkezi",
    "Altyn Zaman söwda merkezi",
    "Altyn Asyr harytşnaslyk merkezi",
    "Uniwermag söwda merkezi",
    "Paýtagt söwda merkezi"
  ]),
  Province(name: "Arkadag", cities: []),
  Province(name: "Ahal", cities: [
    "Änew",
    "Ýaşlyk",
    "Gökdepe",
    "Ak bugdaý",
    "Babadaýhan",
    "Kaka",
    "Tejen",
    "Sarahs",
    "Bäherden",
  ]),
  Province(name: "Daşoguz", cities: [
    "Daşoguz şäheri",
    "Gurbansoltan eje",
    "Boldumsaz",
    "Gubadag",
    "Şabat",
    "Görogly (Tagta)",
    "Akdepe",
    "Köneürgenç",
    "S. Türkmenbaşy",
    "Ruhubelent",
  ]),
  Province(name: "Mary", cities: [
    "Mary şäheri",
    "Ýolöten",
    "Murgap",
    "Sakarçäge",
    "Serhetabat (Guşgy)",
    "Garagum",
    "Wekilbazar",
    "Şatlyk",
    "Baýramaly",
    "Türkmen gala",
    "Oguzhan",
    "Tagtabazar",
  ]),
  Province(name: "Lebap", cities: [
    "Türkmenabat",
    "Halaç",
    "Kerki",
    "Seýdi",
    "Saýat",
    "Sakar",
    "Gazojak",
    "Garabekewül",
    "Farap",
    "Darganata",
    "Dänew",
    "Köýtendag",
    "Hojambaz",
    "Dostluk",
    "Magdanly",
  ]),
  Province(name: "Balkan", cities: [
    "Balkanabat",
    "Türkmenbaşy",
    "Awaza",
    "Jebel",
    "Gumdag",
    "Gyzylarbat",
    "Garaboğaz",
    "Etrek",
    "Esenguly",
    "Magtymguly",
    "Bereket",
  ]),
];

//Russian Location
List<Province> provinces_ru = [
  Province(name: "Ашхабад", cities: [
    "Парахат 1",
    "Парахат 2",
    "Парахат 3",
    "Парахат 4",
    "Парахат 5",
    "Парахат 6",
    "Парахат 7",
    "1-й микрорайон",
    "2-й микрорайон",
    "3-й микрорайон",
    "4-й микрорайон",
    "5-й микрорайон",
    "6-й микрорайон",
    "7-й микрорайон",
    "8-й микрорайон",
    "9-й микрорайон",
    "10-й микрорайон",
    "11-й микрорайон",
    "30-й микрорайон",
    "Ховдан А",
    "Ховдан Б",
    "Ховдан В",
    "13-я этап",
    "14-я этап",
    "15-я этап",
    "16-я этап",
    "Пр Арчабил",
    "Пр Чандыбиль",
    "Пр Нейтралитета (Подвойская)",
    "Пр Независимости (Советская)",
    "Пр Туркменбаши (Ленина)",
    "Пр Нейтрального Туркменистана (Гоголя)",
    "Пр Махтумкули (Свобода)",
    "Ул А. Ниязова",
    "Ул 10 лет Благодарности",
    "Ул Ататюрка",
    "Ул Мати Косаява",
    "Ул Гороглы (Первомайская)",
    "Ул Азади",
    "Ул А. Бердиева (Ереванская)",
    "Ул Таслама",
    "Ул Гундоғар (Магистральная)",
    "Ул Кемине",
    "Ул Багтиярлык",
    "Ул Г.Кулиева (Объездная)",
    "Ул Нагина",
    "Ул Петрозаводская",
    "Олимпийский городок",
    "ДОСААФ",
    "Нефтегаз",
    "Район Ак Алтын",
    "Коши",
    "Район Ким",
    "Тазе заман",
    "Ялкым",
    "Гыпджак",
    "Ясмансалык",
    "Акдашаяк",
    "Бедев",
    "Арзув",
    "Багыр",
    "Чоганлы",
    "Гуртлы",
    "Абадан (Бузмейин)",
    "Хитровка",
    "Промзона",
    "Эксбаза",
    "Геррикгала",
    "Бекреве",
    "Гёкдже",
    "Рухабад (90)",
    "Шор гарадамак",
    "40 лет",
    "Ашхабад Молл",
    "Торговый центр Беркарар",
    "Торговый центр Аркач",
    "Торговый центр Багтиярлык",
    "Торговый центр 15 лет Нейтралитета",
    "Торговый центр Гюльземин",
    "Торговый центр «Ялкым Ашгабата»",
    "Торговый центр «Алтын заман»",
    "Торговый центр «Алтын асыр»",
    "Торговый центр Универмаг",
    "Торговый центр Пайтагт",
  ]),
  Province(name: "Аркадаг", cities: []),
  Province(name: "Ахал", cities: [
    "Аннау",
    "Яшлык",
    "Гёкдепе",
    "Ак бугдай",
    "Бабадайхан",
    "Кака",
    "Теджен",
    "Сaрахс",
    "Бахерден",
  ]),
  Province(name: "Дашогуз", cities: [
    "Дашогуз город",
    "Гурбансолтан-эдже",
    "Болдумсаз",
    "Губадаг",
    "Шабат",
    "Гёроглы (Тахта)",
    "Акдепе",
    "Куня-Ургенч",
    "С. Туркменбаши",
    "Рухубелент",
  ]),
  Province(name: "Мары", cities: [
    "Мары город",
    "Йолотен",
    "Мургап",
    "Сакарчага",
    "Серхетабат (Гушги)",
    "Каракумы",
    "Векильбазар",
    "Шатлык",
    "Байрамали",
    "Туркменкала",
    "Огузхан",
    "Тахтабазар",
  ]),
  Province(name: "Лебап", cities: [
    "Туркменабат",
    "Халач",
    "Керки",
    "Сейди",
    "Саят",
    "Сакар",
    "Газоджак",
    "Карабекаул",
    "Фарап",
    "Дарганата",
    "Дянев",
    "Койтендаг",
    "Ходжамбас",
    "Достлук",
    "Магданлы",
  ]),
  Province(name: "Балкан", cities: [
    "Балканабат",
    "Туркменбаши",
    "Аваза",
    "Джебел",
    "Гумдаг",
    "Гызыларбат",
    "Карабогаз",
    "Этрек",
    "Эcенгулы",
    "Магтымгулы",
    "Берекет",
  ]),
];
